-- AlterTable
ALTER TABLE "settings" ADD COLUMN     "lotSizeCfd" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
ADD COLUMN     "lotSizeCrypto" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "lotSizeEnergies" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "lotSizeForex" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN     "lotSizeIndices" DOUBLE PRECISION NOT NULL DEFAULT 0.1,
ADD COLUMN     "lotSizeMetals" DOUBLE PRECISION NOT NULL DEFAULT 10,
ALTER COLUMN "cryptoAssetsVolumes" SET DEFAULT ARRAY['1.0', '10', '50', '100']::TEXT[],
ALTER COLUMN "energiesAssetsVolumes" SET DEFAULT ARRAY['10', '50', '100', '500']::TEXT[],
ALTER COLUMN "forexAssetsVolumes" SET DEFAULT ARRAY['10000', '50000', '100000', '500000']::TEXT[],
ALTER COLUMN "indicesAssetsVolumes" SET DEFAULT ARRAY['0.1', '1.0', '5.0', '10.0']::TEXT[],
ALTER COLUMN "metalsAssetsVolumes" SET DEFAULT ARRAY['10', '50', '100', '500']::TEXT[];
